baseURL = "https://noahjessop.com/"
languageCode = "en-us"
title = "plain talk by noah jessop"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  post = "/:filename/"

[params]
  description = "writings and more"

[menu]
  [[menu.nav]]
  name = "home"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "start here"
  url = "/about/"
  weight = 2
  [[menu.nav]]
