baseURL = "https://minimal-hugo-blog-layout.netlify.com/"
languageCode = "en-us"
title = "Some blog title"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  post = "/:filename/"

[params]
  description = "Some blog description"

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 2
  [[menu.nav]]
  name = "Contact"
  url = "/contact/"
  weight = 3